before:
  hooks:
    - make clean

builds:
  - binary: reaper
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
    ldflags:
      - "-w -s -X github.com/chanzuckerberg/reaper/pkg/util.GitSha={{.Commit}} -X github.com/chanzuckerberg/reaper/pkg/util.Version={{.Version}} -X github.com/chanzuckerberg/reaper/pkg/util.Dirty=false -X github.com/chanzuckerberg/reaper/pkg/util.Release=true"

archive:
  files:
  - none*

release:
  prerelease: false

brew:
  description: "Don't fear."
  github:
    owner: chanzuckerberg
    name: homebrew-tap
  homepage: "https://github.com/chanzuckerberg/reaper"
  test: system "#{bin}/reaper version"
