before:
  hooks:
    - make clean

builds:
  - binary: reaper
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
    ldflags:
      - -w -s -X github.com/chanzuckerberg/reaper/cmd.GitSha={{.Commit}} -X github.com/chanzuckerberg/reaper/cmd.Version={{.Version}} -X github.com/chanzuckerberg/reaper/cmd.Dirty=false -X github.com/chanzuckerberg/reaper/cmd.Release=true

archives:
  - files:
      - none*

release:
  prerelease: false

brews:
  - description: "Don't fear."
    github:
      owner: chanzuckerberg
      name: homebrew-tap
    homepage: "https://github.com/chanzuckerberg/reaper"
    test: system "#{bin}/reaper version"

dockers:
  - goos: linux
    goarch: amd64
    dockerfile: Dockerfile.release
    binaries:
      - reaper
    image_templates:
      - "chanzuckerberg/reaper:latest"
      - "chanzuckerberg/reaper:v{{ .Version }}"
      - "chanzuckerberg/reaper:v{{ .Major }}"
      - "chanzuckerberg/reaper:v{{ .Major }}.{{ .Minor }}"
