dist: bionic
language: go
go:
  - "1.13.1"
install:
  - npm install -g snyk
  - make setup
  - curl -o $HOME/bin/docker-helper https://raw.githubusercontent.com/chanzuckerberg/infra-tools/ryanking/normalize_docker_tags/docker-helper
  - chmod +x $HOME/bin/docker-helper
jobs:
  include:
    - stage: check
      script:
        - make test-ci
        - bash <(curl -s https://codecov.io/bash)
    - stage: check
      script:
        - snyk monitor --org=czi
        - snyk test
    - stage: build and push
      script:
        - docker-helper build chanzuckerberg/reaper . $TRAVIS_BRANCH ${TRAVIS_COMMIT::8} $TRAVIS_BUILD_NUMBER
        - docker-helper push chanzuckerberg/reaper
