accounts:
  - name: czi-id
    id: 416703108729
    role: czi-admin
  - name: czi-corp
    id: 252147947505
    role: czi-admin
  - name: czi-si
    id: 626314663667
    role: czi-admin
  - name: czi-logs
    id: 724328632434
    role: czi-admin
  - name: meta-2
    id: 607813682535
    role: czi-admin
  - name: edinnovationlabs
    id: 805813389673
    role: czi-admin
  - name: czi-sec
    id: 871040364337
    role: czi-admin
  - name: czi-domains
    id: 382303590750
    role: czi-admin
  - name: czi-physec
    id: 728896018347
    role: czi-admin

policies:
  - name: owner
    resource_selector: "name in (s3, ec2_instance)"
    tag_selector: "!owner"
    label_selector: ""
    max_age: 20000h

    notifications:
      - message_template: >
          Resource {{.ID}} does not have an owner tag.
          Resource was created approximately {{.Age}} ago.
          It will be automatically deleted in {{.TTL}} if owner tag not added.
  
  - name: iam-user-mfa
    resource_selector: "name=iam_user"
    tag_selector: ""
    label_selector: "has_password,!has_mfa"
    max_age: 20000h

    notifications:
      - message_template: >
          IAM User {{.ID}} has a password and no MFA device. Please add an MFA device.

aws_regions:
  - us-east-1
  - us-west-2
  - us-west-1
