policies:
  - name: s3-owner
    resource_selector: ""
    tag_selector: "!owner"
    label_selector: ""
    max_age: 20000h

    notifications:
      - message_template: >
          Resource {{.ID}} does not have an owner tag.
          Resource was created approximately {{.Age}} ago.
          It will be automatically deleted in {{.TTL}} if owner tag not added.

aws_regions:
  - us-east-1
