accounts:
  - name: czi-id
    id: 416703108729
    role: czi-admin
  - name: czi-corp
    id: 252147947505
    role: czi-admin
  - name: czi-si
    id: 626314663667
    role: czi-admin
  - name: czi-logs
    id: 724328632434
    role: czi-admin
  - name: meta-2
    id: 607813682535
    role: czi-admin
  - name: edinnovationlabs
    id: 805813389673
    role: czi-admin
  - name: czi-sec
    id: 871040364337
    role: czi-admin
  - name: czi-domains
    id: 382303590750
    role: czi-admin
  - name: czi-physec
    id: 728896018347
    role: czi-admin

policies:
  - name: owner
    resource_selector: "name in (ec2_instance, s3)"
    tag_selector: "!owner"
    label_selector: ""
    max_age: 20000h

    notifications:
      - recipient: rking@chanzuckerberg.com
        message_template: >
          Resource {{.ID}} in account `{{.AccountName}}` does not have an owner tag.
          Resource was created approximately {{.Age}} ago.
          It will be automatically deleted in {{.TTL}} if owner tag not added.
  

  - name: owner
    resource_selector: "name in (vpc)"
    tag_selector: "!owner"
    label_selector: ""
    max_age: 20000h

    notifications:
      - recipient: rking@chanzuckerberg.com
        message_template: >
          Resource {{.ID}} in account `{{.AccountName}}` does not have an owner tag.
          Resource was created approximately {{.Age}} ago.
          It will be automatically deleted in {{.TTL}} if owner tag not added.
  
  - name: iam-user-mfa
    resource_selector: "name=iam_user"
    tag_selector: ""
    label_selector: "has_password,!has_mfa"
    max_age: 20000h
    notifications:
      - recipient: rking@chanzuckerberg.com
        message_template: >
          IAM User {{.ResourceID}} in account `{{.AccountName}}` has a password and no MFA device. <https://www.google.com/|google>
      - recipient: $owner
        message_template: >
          Your IAM user in account `{{.AccountName}}` has a password but no MFA device. Please add an MFA device ASAP.
          See AWS docs for this <https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_mfa_enable_virtual.html|here>
          And ask in <#help-infra> if you need assistance.

aws_regions:
  - us-east-1
  - us-west-2
  - us-west-1
