[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.15.36"

[[constraint]]
  branch = "master"
  name = "github.com/blend/go-sdk"

[[constraint]]
  branch = "ryanking/vpc"
  name = "github.com/chanzuckerberg/go-misc"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/hashicorp/go-multierror"
  version = "1.0.0"

[[constraint]]
  name = "github.com/docker/go-units"
  version = "0.3.3"

[[constraint]]
  branch = "master"
  name = "github.com/olekukonko/tablewriter"

[[constraint]]
  name = "github.com/Masterminds/sprig"
  version = "2.16.0"

[[constraint]]
  name = "github.com/apparentlymart/go-cidr"
  version = "1.0.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"
